In [1]:
from terminal import *

FMP API key loaded successfully. Length: 32, First chars: ESo...
FMP rate limit interval set to 0.1 seconds

In [2]:
f("AAPL MSFT GOOGL")

  ticker  weight
0   AAPL     1.0
1   MSFT     1.0
2  GOOGL     1.0

In [5]:
f("AAPL MSFT -> .mcap()")

  ticker  weight           mcap
0   AAPL     1.0  2996569554000
1   MSFT     1.0  3476050307200